; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35217.0 

	TITLE	C:\Users\Hamzzi\Desktop\AI_Practice\Source\VS2010\Buckland_Chapter7 to 10_Raven\Debug\Goal_StrafePattern.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
